### ISSUE TITLE
Game crash with Galacticraft Space Station dimension

### ISSUE THREAD

**Issue by QuantumStatement** [SilentChaos512/ExtendedDays#20]
### Versions

Minecraft Version: 1.11.2
Extended Days Version: 0.2.3
Silent Lib Version: 2.2.6
Galacticraft version: 4.0.1.174

### Expected behavior

- Player successfully arrive on Space Station

### Actual behaviour

- Game crashes when player arrive on Space Station
[Crash Report](https://github.com/SilentChaos512/ExtendedDays/files/1960647/crash-2018-04-30_16.04.07-client.txt)

### Steps to reproduce the problem

1. Add Extended days and Galacticraft in mod pack
2. Fly on Space Station
3. ...
4. Profit

Also see [Galacticraft#3379](https://github.com/micdoodle8/Galacticraft/issues/3379)

**Comment by SilentChaos512** [comment]
OK, thanks. I should have been checking that I can actually cast the class. I'll add a blacklist to the config as well. And I apologize for letting this sit so long, no idea how I missed this.

**Comment by radfast** [comment]
No worries :)  Happy that you will be fixing it at all!

BUT:  it's **our** class cast which is failing here.  The real concern is that you are overriding our `skyProvider` at all, we need to have total control over the skyProvider in all our space dimensions otherwise they are going to look mighty strange, with blue skies etc in space...

For your blacklist our default dimension IDs are -28 through to -32.  But also any unused positive dimension ID from 2 onwards can be created dynamically as a Galacticraft space dimension if a player creates their own space station.  (One dimension like this can be created per player, on a multiplayer server.)  And Galacticraft third party add-ons add even more planets with negative dimension IDs.

Can I suggest it might be better if you check the `WorldProvider` class and see if it's a vanilla `WorldProviderSurface` - or call `WorldProvider.getDimensionType` and see if that's `DimensionType.OVERWORLD`?   This check should be enough for you to avoid all the Galacticraft dimensions (and it's add-ons) and should be future proof, without players needing to set up configs correctly.

**Comment by SilentChaos512** [comment]
Fixed in 0.2.5
